#!/usr/bin/env bash
set -euo pipefail

catalog_path="${1:-cards/catalog.tsv}"
datasets_path="${2:-cards/datasets.tsv}"
out_dir="${3:-cards/generated}"
samples_build_dir="${SAMPLES_BUILD_DIR:-build/samples}"
default_pat="${SAMPLES_FILE_PATTERN:-nu_selection.root,nu_selection_data.root}"

if [ ! -f "$catalog_path" ]; then
  echo "render-sample-catalog: missing catalog: $catalog_path" >&2
  exit 1
fi

if [ ! -f "$datasets_path" ]; then
  echo "render-sample-catalog: missing datasets file: $datasets_path" >&2
  exit 1
fi

mkdir -p "$out_dir"

datasets_mk="$out_dir/datasets.mk"

awk -F '\t' -v default_pat="$default_pat" '
  BEGIN {
    print "# Generated by tools/render-sample-catalog.sh"
    print ""
    print "pat ?= " default_pat
    print ""
  }
  /^[[:space:]]*#/ || NF == 0 { next }
  FNR == 1 && $1 == "dataset_key" { next }
  {
    if (NF != 4) {
      printf("render-sample-catalog: expected 4 fields in %s at line %d\n", FILENAME, FNR) > "/dev/stderr"
      exit 1
    }
    dataset[++n] = $1
    context[$1] = $2
    base[$1] = $3
    out[$1] = $4
  }
  END {
    printf("datasets :=")
    for (i = 1; i <= n; ++i)
      printf(" %s", dataset[i])
    printf("\n\n")
    for (i = 1; i <= n; ++i) {
      key = dataset[i]
      printf("name.%s := %s\n", key, context[key])
      printf("base.%s := %s\n", key, base[key])
      printf("out.%s := %s\n\n", key, out[key])
    }
  }
' "$datasets_path" > "$datasets_mk"

while IFS=$'\t' read -r dataset_key context base_dir list_dir; do
  [ -n "$dataset_key" ] || continue

  awk -F '\t' -v dataset="$dataset_key" -v out_dir="$out_dir" -v context="$context" '
    function merge_scope(current, candidate, label) {
      if (candidate == "" || candidate == "-")
        return current
      if (current == "")
        return candidate
      if (current != candidate) {
        printf("render-sample-catalog: inconsistent %s for dataset %s (%s vs %s)\n", label, dataset, current, candidate) > "/dev/stderr"
        exit 1
      }
      return current
    }
    function infer_run(value,    cleaned, fields, n, i, candidate) {
      cleaned = value
      gsub(/[^[:alnum:]]+/, " ", cleaned)
      n = split(cleaned, fields, /[[:space:]]+/)
      candidate = ""
      for (i = 1; i <= n; ++i) {
        if (fields[i] !~ /^run[0-9][[:alnum:]]*$/)
          continue
        if (candidate == "")
          candidate = fields[i]
        else if (candidate != fields[i]) {
          printf("render-sample-catalog: inconsistent inferred run for dataset %s (%s vs %s)\n", dataset, candidate, fields[i]) > "/dev/stderr"
          exit 1
        }
      }
      return candidate
    }
    function require_valid_row() {
      if (NF != 14) {
        printf("render-sample-catalog: expected 14 fields in %s at line %d\n", FILENAME, FNR) > "/dev/stderr"
        exit 1
      }
      if ($4 != "dir" && $4 != "list" && $4 != "samdef") {
        printf("render-sample-catalog: unsupported source kind %s for %s in dataset %s\n", $4, $2, dataset) > "/dev/stderr"
        exit 1
      }
      if ($5 == "" || $5 == "-") {
        printf("render-sample-catalog: empty source ref for %s in dataset %s\n", $2, dataset) > "/dev/stderr"
        exit 1
      }
      if ($7 == "detector" && ($8 == "" || $8 == "-")) {
        printf("render-sample-catalog: detector row %s in dataset %s is missing a logical nominal key\n", $2, dataset) > "/dev/stderr"
        exit 1
      }
    }
    /^[[:space:]]*#/ || NF == 0 { next }
    FNR == 1 && $1 == "dataset_key" { next }
    $1 != dataset { next }
    {
      require_valid_row()
      artifact[++n] = $2
      source_kind[n] = $4
      source_ref[n] = $5
      origin[n] = $6
      variation[n] = $7
      beam[n] = $13
      polarity[n] = $14
      dataset_beam = merge_scope(dataset_beam, $13, "beam")
      dataset_polarity = merge_scope(dataset_polarity, $14, "polarity")
      dataset_campaign = merge_scope(dataset_campaign, $12, "campaign")
      dataset_run = merge_scope(dataset_run, infer_run(dataset " " context " " $11 " " $12), "run")
      logical[n] = $3
      if (!(logical[n] in seen_logical)) {
        seen_logical[logical[n]] = 1
        logical_order[++m] = logical[n]
        logical_origin[logical[n]] = $6
        logical_variation[logical[n]] = $7
        logical_beam[logical[n]] = $13
        logical_polarity[logical[n]] = $14
      } else {
        if (logical_origin[logical[n]] != $6 ||
            logical_variation[logical[n]] != $7 ||
            logical_beam[logical[n]] != $13 ||
            logical_polarity[logical[n]] != $14) {
          printf("render-sample-catalog: inconsistent build metadata for logical sample %s in dataset %s\n", logical[n], dataset) > "/dev/stderr"
          exit 1
        }
      }
      if (logical_artifacts[logical[n]] != "")
        logical_artifacts[logical[n]] = logical_artifacts[logical[n]] " " artifact[n]
      else
        logical_artifacts[logical[n]] = artifact[n]
    }
    END {
      if (n == 0) {
        printf("render-sample-catalog: no catalog rows for dataset %s\n", dataset) > "/dev/stderr"
        exit 1
      }
      printf("samples.%s := \\\n", dataset)
      for (i = 1; i <= n; ++i)
        printf("\t%s%s\n", artifact[i], (i < n ? " \\" : ""))
      printf("\n")
      printf("logical_samples.%s := \\\n", dataset)
      for (i = 1; i <= m; ++i)
        printf("\t%s%s\n", logical_order[i], (i < m ? " \\" : ""))
      printf("\n")
      printf("dataset_defs.%s := %s/%s.sample.defs\n", dataset, out_dir, dataset)
      printf("dataset_manifest.%s := %s/%s.dataset.manifest\n\n", dataset, out_dir, dataset)
      if (dataset_run == "") {
        printf("render-sample-catalog: could not infer run for dataset %s\n", dataset) > "/dev/stderr"
        exit 1
      }
      printf("dataset_run.%s := %s\n", dataset, dataset_run)
      printf("dataset_beam.%s := %s\n", dataset, dataset_beam)
      printf("dataset_polarity.%s := %s\n", dataset, dataset_polarity)
      if (dataset_campaign != "")
        printf("dataset_campaign.%s := %s\n", dataset, dataset_campaign)
      printf("\n")
      for (i = 1; i <= m; ++i) {
        logical_key = logical_order[i]
        printf("sample_manifest.%s.%s := %s/%s.%s.sample.manifest\n", dataset, logical_key, out_dir, dataset, logical_key)
        printf("sample_artifacts.%s.%s := %s\n", dataset, logical_key, logical_artifacts[logical_key])
        printf("sample_origin.%s.%s := %s\n", dataset, logical_key, logical_origin[logical_key])
        printf("sample_variation.%s.%s := %s\n", dataset, logical_key, logical_variation[logical_key])
        printf("sample_beam.%s.%s := %s\n", dataset, logical_key, logical_beam[logical_key])
        printf("sample_polarity.%s.%s := %s\n", dataset, logical_key, logical_polarity[logical_key])
      }
      printf("\n")
      for (i = 1; i <= n; ++i) {
        printf("sample_source_kind.%s.%s := %s\n", dataset, artifact[i], source_kind[i])
        printf("sample_source_ref.%s.%s := %s\n", dataset, artifact[i], source_ref[i])
      }
      printf("\n")
    }
  ' "$catalog_path" >> "$datasets_mk"

  defs_path="$out_dir/$dataset_key.sample.defs"
  awk -F '\t' -v dataset="$dataset_key" '
    function require_valid_row() {
      if (NF != 14) {
        printf("render-sample-catalog: expected 14 fields in %s at line %d\n", FILENAME, FNR) > "/dev/stderr"
        exit 1
      }
      if ($4 != "dir" && $4 != "list" && $4 != "samdef") {
        printf("render-sample-catalog: unsupported source kind %s for %s in dataset %s\n", $4, $2, dataset) > "/dev/stderr"
        exit 1
      }
      if ($5 == "" || $5 == "-") {
        printf("render-sample-catalog: empty source ref for %s in dataset %s\n", $2, dataset) > "/dev/stderr"
        exit 1
      }
      if ($7 == "detector" && ($8 == "" || $8 == "-")) {
        printf("render-sample-catalog: detector row %s in dataset %s is missing a logical nominal key\n", $2, dataset) > "/dev/stderr"
        exit 1
      }
    }
    BEGIN {
      print "# Generated by tools/render-sample-catalog.sh"
      print "# key variation nominal tag role defname campaign"
    }
    /^[[:space:]]*#/ || NF == 0 { next }
    FNR == 1 && $1 == "dataset_key" { next }
    $1 != dataset { next }
    {
      require_valid_row()
      logical = $3
      metadata = $7 "\t" $8 "\t" $9 "\t" $10 "\t" $11 "\t" $12
      if (!(logical in seen)) {
        seen[logical] = 1
        order[++n] = logical
        meta[logical] = metadata
        logical_variation[logical] = $7
        logical_nominal[logical] = $8
      } else if (meta[logical] != metadata) {
        printf("render-sample-catalog: inconsistent logical metadata for %s in dataset %s\n", logical, dataset) > "/dev/stderr"
        exit 1
      }
    }
    END {
      for (i = 1; i <= n; ++i) {
        logical = order[i]
        if (logical_variation[logical] == "detector" && !(logical_nominal[logical] in seen)) {
          printf("render-sample-catalog: detector logical key %s in dataset %s points at missing nominal %s\n", logical, dataset, logical_nominal[logical]) > "/dev/stderr"
          exit 1
        }
      }
      for (i = 1; i <= n; ++i) {
        logical = order[i]
        print logical "\t" meta[logical]
      }
    }
  ' "$catalog_path" > "$defs_path"

  rm -f "$out_dir/$dataset_key".*.sample.manifest
  awk -F '\t' -v dataset="$dataset_key" -v list_dir="$list_dir" -v out_dir="$out_dir" '
    function require_valid_row() {
      if (NF != 14) {
        printf("render-sample-catalog: expected 14 fields in %s at line %d\n", FILENAME, FNR) > "/dev/stderr"
        exit 1
      }
      if ($4 != "dir" && $4 != "list" && $4 != "samdef") {
        printf("render-sample-catalog: unsupported source kind %s for %s in dataset %s\n", $4, $2, dataset) > "/dev/stderr"
        exit 1
      }
      if ($5 == "" || $5 == "-") {
        printf("render-sample-catalog: empty source ref for %s in dataset %s\n", $2, dataset) > "/dev/stderr"
        exit 1
      }
    }
    BEGIN {
      current_logical = ""
    }
    /^[[:space:]]*#/ || NF == 0 { next }
    FNR == 1 && $1 == "dataset_key" { next }
    $1 != dataset { next }
    {
      require_valid_row()
      logical = $3
      manifest_path = out_dir "/" dataset "." logical ".sample.manifest"
      if (!(logical in seen)) {
        seen[logical] = 1
        print "# Generated by tools/render-sample-catalog.sh" > manifest_path
        print "# shard sample_list_path" >> manifest_path
      }
      print $2 "\t" list_dir "/" $2 ".list" >> manifest_path
      close(manifest_path)
    }
  ' "$catalog_path"

  manifest_path="$out_dir/$dataset_key.dataset.manifest"
  awk -F '\t' -v dataset="$dataset_key" -v samples_build_dir="$samples_build_dir" -v context="$context" '
    function require_valid_row() {
      if (NF != 14) {
        printf("render-sample-catalog: expected 14 fields in %s at line %d\n", FILENAME, FNR) > "/dev/stderr"
        exit 1
      }
      if ($4 != "dir" && $4 != "list" && $4 != "samdef") {
        printf("render-sample-catalog: unsupported source kind %s for %s in dataset %s\n", $4, $2, dataset) > "/dev/stderr"
        exit 1
      }
      if ($5 == "" || $5 == "-") {
        printf("render-sample-catalog: empty source ref for %s in dataset %s\n", $2, dataset) > "/dev/stderr"
        exit 1
      }
    }
    BEGIN {
      print "# Generated by tools/render-sample-catalog.sh"
      print "# context: " context
      print "# logical_key sample_root_path"
    }
    /^[[:space:]]*#/ || NF == 0 { next }
    FNR == 1 && $1 == "dataset_key" { next }
    $1 != dataset { next }
    {
      require_valid_row()
      logical = $3
      if (!(logical in seen)) {
        seen[logical] = 1
        order[++n] = logical
      }
    }
    END {
      for (i = 1; i <= n; ++i)
        print order[i] "\t" samples_build_dir "/" dataset "/" order[i] ".root"
    }
  ' "$catalog_path" > "$manifest_path"
done < <(
  awk -F '\t' '
    /^[[:space:]]*#/ || NF == 0 { next }
    FNR == 1 && $1 == "dataset_key" { next }
    { print $1 "\t" $2 "\t" $3 "\t" $4 }
  ' "$datasets_path"
)

awk '
  { lines[++n] = $0 }
  END {
    while (n > 0 && lines[n] == "")
      --n
    for (i = 1; i <= n; ++i)
      print lines[i]
  }
' "$datasets_mk" > "$datasets_mk.tmp"
mv "$datasets_mk.tmp" "$datasets_mk"

echo "render-sample-catalog: wrote $datasets_mk"
